"""Type stubs for py7zr."""

from typing import Any, Iterator, List

class ArchiveInfo:
    filename: str
    uncompressed: int
    is_directory: bool

class SevenZipFile:
    def __init__(self, file: str, mode: str = "r") -> None: ...
    def __enter__(self) -> "SevenZipFile": ...
    def __exit__(self, *args: Any) -> None: ...
    def list(self) -> List[ArchiveInfo]: ...
    def extractall(self, path: str = ".") -> None: ...
