"""Type stubs for rarfile."""

from typing import Any, BinaryIO, Iterator, List

class RarInfo:
    filename: str
    file_size: int
    def is_dir(self) -> bool: ...

class RarFile:
    def __init__(self, file: str, mode: str = "r") -> None: ...
    def __enter__(self) -> "RarFile": ...
    def __exit__(self, *args: Any) -> None: ...
    def infolist(self) -> List[RarInfo]: ...
    def open(self, member: RarInfo) -> BinaryIO: ...
